spring:
  profiles:
    active:
      - dev
---

spring:
  profiles: dev #开发环境
  application:
    name: ms-cloud-config-zh-dev

---

spring:
  profiles: test
  application:
    name: ms-cloud-config-zh-test